### ISSUE TITLE
Issue with running compiled executable on macOS

### ISSUE THREAD

**Issue by andermoran** [enfiskutensykkel/bf-compiler#2]
On macOS (10.12.2) when running ./out.o it returns
`dyld: malformed mach-o image: missing __LINKEDIT segment`

**Comment by enfiskutensykkel** [comment]
It seems that the newer version of macOS has an even stricter enforcement of the segments it expects.

**Comment by enfiskutensykkel** [comment]
Should work now on macOS 10.12.3
